# Generated by Django 5.1.7 on 2025-04-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='video_url',
            field=models.FileField(blank=True, help_text='Téléchargez une vidéo', null=True, upload_to='jeux/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
