# Generated by Django 5.1.7 on 2025-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0002_alter_jeu_video_url_alter_post_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
