# Generated by Django 5.1.7 on 2025-04-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0003_alter_like_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.FileField(blank=True, help_text='Téléchargez une vidéo', null=True, upload_to='posts/videos/'),
        ),
    ]
